var posur = {
  type: "FeatureCollection",
  name: "poinsurvey",
  crs: { type: "name", properties: { name: "urn:ogc:def:crs:OGC:1.3:CRS84" } },
  features: [
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Watu Cepit",
        Class: "Wisata Alam",
        Desc_: "Dua tebing yang mengapit aliran sumber mata air dari Gunung Kelud",
        idi: "watu",
      },
      geometry: { type: "Point", coordinates: [112.276844019448887, -7.882884536201213, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Kampung Ledokan Jaran Kepang",
        Class: "Wisata Budaya",
        Desc_: "Kampung dengan budaya jaran kepang yang masih terjaga",
        idi: "kampung",
      },
      geometry: { type: "Point", coordinates: [112.278486953413761, -7.880659213196588, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Basecamp Lamor Cofee",
        Class: "Fasilitas Penunjang",
        Desc_: "Warung yang menyajikan Kopi Lamor sebagai produk khas Desa Puncu",
        idi: "lamor",
      },
      geometry: { type: "Point", coordinates: [112.2811530611053, -7.882753969114797, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Edu Wisata Saung Ilmu",
        Class: "Wisata Edukasi",
        Desc_: "Pusat edukasi, pusat interaksi dan pusat perencanaan program pemberdayaan masyarakat",
        idi: "saung",
      },
      geometry: { type: "Point", coordinates: [112.281416174539785, -7.882627456867031, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Situs Jeding Miring",
        Class: "Wisata Alam",
        Desc_: "Situs bak mandi peninggalan zaman Majapahit",
        idi: "jeding",
      },
      geometry: { type: "Point", coordinates: [112.274235658446543, -7.887646962421166, 0.0] },
    },
    {
      type: "Feature",
      properties: { id: 0, Name: "Eduwisata Kopi Dawul", Class: "Wisata Edukasi", Desc_: null, idi: "dawul" },
      geometry: { type: "Point", coordinates: [112.27514008546089, -7.88621965958336, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Camping Ground",
        Class: "Wisata Alam",
        Desc_: "Potensi untuk dijadikan sebagai camping ground di Desa Puncu",
        idi: "camp2",
      },
      geometry: { type: "Point", coordinates: [112.287408410177179, -7.910302293149813, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Air Terjun Desa Puncu",
        Class: "Wisata Alam",
        Desc_: "Air terjun yang terletak di kaki Gunung Kelud",
        idi: "terjun",
      },
      geometry: { type: "Point", coordinates: [112.294237159468878, -7.91852494931176, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Goa Nippon",
        Class: "Wisata Alam",
        Desc_: "Unsur geografis berupa gua dan bendungan air zaman dahulu",
        idi: "gua",
      },
      geometry: { type: "Point", coordinates: [112.286043636319135, -7.894308994584002, 0.0] },
    },
    {
      type: "Feature",
      properties: { id: 0, Name: "Edukasi Kopi", Class: "Wisata Edukasi", Desc_: null, idi: "kopi" },
      geometry: { type: "Point", coordinates: [112.296210306894054, -7.899393637332182, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Edukasi Cabe",
        Class: "Wisata Edukasi",
        Desc_: "Wisata edukasi budi daya tanaman cabai di Dusun Laharpang",
        idi: "cabe",
      },
      geometry: { type: "Point", coordinates: [112.28058698088816, -7.886100447131916, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Warung Mongso",
        Class: "Fasilitas Penunjang",
        Desc_: "Tempat peristirahatan atau tempat berkumpul sebelum atau setelah mendaki Gunung Kelud",
        idi: "mongso",
      },
      geometry: { type: "Point", coordinates: [112.270758250443365, -7.866797708377768, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Pos Pendakian Laharpang",
        Class: "Wisata Alam",
        Desc_: "Titik keberangkatan pendakian menuju Gunung Kelud",
        idi: "kelud",
      },
      geometry: { type: "Point", coordinates: [112.293120859040215, -7.903839606703485, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Perkebunan Kayu Jabon",
        Class: "Wisata Alam",
        Desc_: "Perkebunan penghasil kayu jabon di Dusun Mankli, memiliki estetika yang khas dengan pohon-pohon menjulang tinggi",
        idi: "jabon",
      },
      geometry: { type: "Point", coordinates: [112.255476312046625, -7.866611540849566, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Pabrik Penghasil Gula",
        Class: "Wisata Edukasi",
        Desc_: "Pabrik peninggalan Belanda yang digunakan untuk memproduksi gula",
        idi: "pabrik",
      },
      geometry: { type: "Point", coordinates: [112.25855, -7.866881, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Perkebunan Tebu",
        Class: "Wisata Alam",
        Desc_: "Bahan baku pembuatan gula oleh pabrik peninggalan Belanda",
        idi: "Tebu",
      },
      geometry: { type: "Point", coordinates: [112.261211, -7.869515, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Spot Foto Perkebunan Mankli",
        Class: "Wisata Alam",
        Desc_: "Hamparan kebun nanas yang indah di rute offroad",
        idi: "nanas2",
      },
      geometry: { type: "Point", coordinates: [112.263167, -7.871497, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Sunset Point Perkebunan Mankli",
        Class: "Wisata Alam",
        Desc_: "Lanjutan dari hamparan kebun nanas di atas bukit yang cukup tinggi untuk melihat sunset",
        idi: "sunset",
      },
      geometry: { type: "Point", coordinates: [112.267243, -7.876006, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Sunrise Point Mankli",
        Class: "Wisata Alam",
        Desc_: "Tempat melihat matahari terbit di tengah kebun nanas",
        idi: "sunrise",
      },
      geometry: { type: "Point", coordinates: [112.269906, -7.878339, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Potensi Camping Point Mankli",
        Class: "Wisata Alam",
        Desc_: "Hamparan kosong yang cukup lapang untuk menjadi tempat bermalam",
        idi: "camp",
      },
      geometry: { type: "Point", coordinates: [112.271214, -7.878781, 0.0] },
    },
    {
      type: "Feature",
      properties: {
        id: 0,
        Name: "Pintu Masuk Dusun Damarwulan",
        Class: "Batas Dusun",
        Desc_: "Gapura sebagai tanda memasuki Dusun Damarwulan",
        idi: null,
      },
      geometry: { type: "Point", coordinates: [112.276052316937822, -7.886496874075413, 0.0] },
    },
  ],
};
